# Generated by Django 6.0 on 2025-12-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('FaceId', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('OnPinecone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('ImageId', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('OnPinecone', models.BooleanField(default=False)),
                ('IsFaceRecognised', models.BooleanField(default=False)),
                ('Faces', models.ManyToManyField(to='photo_service.face')),
            ],
        ),
        migrations.AddField(
            model_name='face',
            name='Images',
            field=models.ManyToManyField(to='photo_service.image'),
        ),
    ]
