# Generated by Django 6.0 on 2026-02-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='AlbumId',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='Caption',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='CreatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='FaceCount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='ObjectName',
            field=models.CharField(null=True),
        ),
    ]
